---
- hosts: webapp
  become: yes
  tasks:
  - name: Install Apache Ubuntu
    package:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Install Apache CentOS
    package:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: Update Index Page
    copy:
      dest: /var/www/html/index.html
      content: <h1>Welcome To Apache Server</h1>

  - name: Update PHP Page
    copy:
      dest: /var/www/html/date.php
      src: /home/centos/playbooks/date.php

  - name: Install PHP
    package:
      name: php
      state: present

  - name: Restart Apache Ubuntu
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"

  - name: Restart Apache CentOs
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"
...
