---
- hosts: webapp
  become: yes
  tasks:
  - name: Install Apache
    package:
      name: httpd
      state: present


  - name: Update Index Page
    copy:
      dest: /var/www/html/index.html
      content: <h1>Welcome To Apache Server</h1>

  - name: Update Apache Port Config
    copy:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.conf

  - name: Update SELInux
    selinux:
      policy: targeted
      state: permissive

  - name: Restart Apache
    service:
      name: httpd
      state: restarted

  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes
...
