---
- hosts: webapp
  become: yes
  vars:
    username: ravi
    apache_port: 9090
    doc_root: /var/www/html
  tasks:
  - name: Update SELInux
    selinux:
      policy: targeted
      state: permissive
    when: ansible_os_family == "RedHat"

  - name: Install Apache Ubuntu
    package:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Install Apache CentOS
    package:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"


  - name: Update Index Page
    copy:
      dest: /var/www/html/index.html
      content: <h1>Welcome To Apache Server</h1>

  - name: Update Static Page
    copy:
      dest: /var/www/html/static.html
      src: /home/centos/playbooks/static.html

  - name: Update Dynamic Page
    template:
      dest: /var/www/html/dynamic.html
      src: /home/centos/playbooks/dynamic.j2

  - name: Update PHP Page
    copy:
      dest: /var/www/html/date.php
      src: /home/centos/playbooks/date.php

  - name: Install PHP
    package:
      name: php
      state: present

  - name: Restart Apache Ubuntu
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"

  - name: Update Apache Port Config
    template:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.j2
    when: ansible_os_family == "RedHat"

  - name: Restart Apache CentOs
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"
...
